# === Project configuration ===
project_name: "path-integration-rnn"
model_type: "multitimescale"
devices: [0, 1, 2, 3] # List of GPU IDs
accelerator: "gpu"
seed: 0 # Global seed

# === Data (trajectory) configuration ===
num_trajectories: 100000
trajectory_type: 'ornstein_uhlenbeck' #'random_walk'
batch_size: 500 #200
num_workers: 7
train_val_split: 0.8
velocity_representation: 'polar'
dt: 0.1 #0.1s (reasonable neural dynamics timescale)
num_time_steps: 20
speed_scale: 0.2

# Specific to 'ornstein_uhlenbeck' trajectory generation
sigma_speed: 0.5
tau_vel: 1

#Specific to 'random_walk'
sigma_rotation: 11.52
border_region: 0.03

# Place cell configuration
arena_size: 2.2
num_place_cells: 512
place_cell_rf: 0.2
surround_scale: 2
DoG: true
place_cell_layout: 'random' #'uniform'

# === RNN configuration == 
input_size: 2
hidden_size: 4096
activation: "ReLU" #"Tanh"

# Timescales configuration

timescales_config:
  type: "discrete"
  values: [0.1443] # alpha 0.5
  #values: [0.001, 0.1, 0.2, 0.448, 0.7, 0.9] # corresponds to [1, 0.2] alpha


# === Training configuration ===
learning_rate: 1.0e-4
weight_decay: 1.0e-4
step_size: 100
gamma: 0.5
max_epochs: 200

# === Callback configs ===
decode_k: 3
log_every_n_epochs: 1
viz_log_every_n_epochs: 10